project/homefood/urls.py
from django.conf.urls import url, handler404, handler500
from . import views

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "homefood"

urlpatterns = [
    url(r"^$", views.IndexView.as_view(), name="index"),
    url(r'^about/$', views.AboutView.as_view(), name="about"),
    url(r'^syllabus/$', views.SyllabusView.as_view(), name="syllabus"),
    url(r'^courses/$', views.CoursesView.as_view(), name='courses'),
    url(r'^enroll/$', views.EnrollView.as_view(), name='enroll'),
    url(r'^schedule/$', views.ScheduleView.as_view(), name='schedule'),
    url(r'^ajax/availability/$', views.get_availability, name='get_availability'),
    url(r'^appointment/$', views.AppointmentView.as_view(), name="appointment"),
    url(r'^success/$', views.SuccessView.as_view(), name='success'),
    url(r'^error/$', views.ErrorView.as_view(), name='success')
]

urlpatterns += staticfiles_urlpatterns()
#
# handler404 = views.handler404
# handler500 = views.handler500

project/project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^homefood/', include('homefood.urls')),
    url(r'^user/', include('users.urls'))
]

project/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "users"

urlpatterns = [
    url(r'^signup/$', views.SignupView.as_view(), name="signup"),
    url(r'^register/$', views.RegisterView.as_view(), name="register"),
    url(r'^home/$', views.HomeView.as_view(), name="home"),
    url(r'^login/$', views.AuthView.as_view(), name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'users/register.html'}, name='logout'),
]

urlpatterns += staticfiles_urlpatterns()

project/homefood/models.py
from __future__ import unicode_literals

from django.db import models
from django import forms
from django.forms import Form, ModelForm

import uuid

from constants import Constants, InterviewConstants
from users.models import CustomUser

# class Location(models.Model):
#     latlong = models.CharField(max_length=200, primary_key=True)
#     latitude = models.CharField(max_length=100)
#     longitude = models.CharField(max_length=100)
#     street = models.CharField(max_length=100)
#     city = models.CharField(max_length=100)
#     state = models.CharField(max_length=50)
#     country = models.CharField(max_length=50)
#
#
# class User(models.Model):
#     user_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
#     user_first_name = models.CharField(max_length=40)
#     user_last_name = models.CharField(max_length=40)
#     user_email = models.EmailField()
#     is_cook = models.BooleanField
#     latitude = models.CharField(max_length=100)
#     longitude = models.CharField(max_length=100)
#     latlong = models.ForeignKey(Location, on_delete=models.CASCADE)
#
#
# class Food(models.Model):
#     food_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
#     food_name = models.CharField(max_length=50)
#     food_cost = models.DecimalField(max_digits=5, decimal_places=2)
#     food_quantity = models.FloatField()
#     food_units = models.CharField(max_length=10)
#     food_description = models.CharField(max_length=1000)
#     user_id = models.ForeignKey(User, on_delete=models.CASCADE)
#
#
# class Order(models.Model):
#     order_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
#     order_date_time = models.DateTimeField(format(Constants.DATE_TIME_FORMAT))
#     order_total = models.DecimalField(max_digits=8, decimal_places=2)
#     user_id = models.ForeignKey(User, on_delete=models.CASCADE)
#
# class Payment(models.Model):
#     payment_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)


# class Schedule(models.Model):
#     interview_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
#     interviewDate = models.DateTimeField(Constants.DATE_FORMAT)
#     interviewTime = models.DateTimeField(Constants.TIME_FORMAT)
#     email = models.EmailField()


########### forms #############
# class AddUserForm(ModelForm):
#     class Meta:
#         model = User
#         fields = ["user_first_name", "user_last_name", "user_email"]
#
#
# class AddFoodProductForm(ModelForm):
#     class Meta:
#         model = Food
#         fields = ["food_name", "food_cost", "food_quantity", "food_units",
#                   "food_description"]
#
# class AddLocation(ModelForm):
#     class Meta:
#         model = Location
#         fields = ["latlong", "latitude", "longitude", "street", "city", "state", "country"]

class Appointments(models.Model):
    interview_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    interview_date = models.CharField(max_length=30, default="")
    interview_time = models.CharField(max_length=30, default="")
    interview_topic = models.CharField(max_length=50, default=InterviewConstants.DEFAULT_INTERVIEW_TOPIC)
    interview_duration = models.CharField(max_length=30, default=InterviewConstants.DEFAULT_INTERVIEW_DURATION_IN_MINS)
    interviewee_email = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    interviewer_email = models.EmailField()
    interview_status = models.CharField(max_length=30, default=InterviewConstants.INTERVIEW_STATUS_SCHEDULED)
    interview_metadata = models.CharField(max_length=30000, default="")

    def __str__(self):
        return str(self.interview_id) + ", interview_date=" + str(self.interview_date) + ", interview_topic=" \
               + str(self.interview_topic) + ", interviewee_email=" + str(self.interviewee_email)

class SchedulerForm(Form):
    scheduleDate = forms.CharField()
    scheduleTime = forms.CharField()
    scheduleTopic = forms.CharField()

project/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    """
    A form that creates a custom user with privileges, from the given email and
    password
    """
    def __init__(self, *args, **kargs):
        super(CustomUserCreationForm, self).__init__(*args, **kargs)
        # We do this because, by default django requires password1 & password2.
        # But in our case, we only want the user to enter password once.
        self.fields.pop('password2')

    class Meta:
        model = CustomUser
        fields = ("name", "email", "password1")


class AuthForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

project/homefood/views.py
from django.core import serializers
from django.shortcuts import render
from django.http import JsonResponse, Http404
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import SchedulerForm

from messages.messages import ScheduleMessage
from homefood.constants import InterviewConstants
from homefood.dao.appointments_dao import AppointmentsDao
from common.util.log.Logger import Logger
from homefood.manager.schedule_manager import ScheduleManager
from homefood.manager.task_manager import TaskManager

PAGE_TEMPLATE = "%s:%s"
INDEX_URL = PAGE_TEMPLATE % ("homefood", "index")
LOG = Logger().get_logger()


class IndexView(ListView):
    template_name = "homefood/interview.html"
    #context_object_name = "all_products"

    def get_queryset(self):
        return ""

class AboutView(ListView):
    template_name = "homefood/about.html"
    #context_object_name = "all_products"

    def get_queryset(self):
        return ""

class SyllabusView(ListView):
    template_name = "homefood/syllabus.html"
    #context_object_name = "all_products"

    def get_queryset(self):
        return ""

class EnrollView(ListView):
    template_name = "homefood/enroll.html"
    #context_object_name = "all_products"

    def get_queryset(self):
        return ""

class CoursesView(ListView):
    template_name = "homefood/courses.html"
    #context_object_name = "all_products"

    def get_queryset(self):
        return ""

@method_decorator(login_required, name="dispatch")
class ScheduleView(LoginRequiredMixin, ListView):
    template_name = "homefood/schedule.html"
    context_object_name = "availabilities"

    def get_queryset(self):
        return ""

    @method_decorator(login_required(login_url="users/register.html"))
    def dispatch(self, *args, **kwargs):
        return super(ScheduleView, self).dispatch(*args, **kwargs)


def get_availability(request):
    date = request.GET.get("date", None)
    scheduler = ScheduleManager()
    availability = scheduler.get_availability(date)
    result = {
        "availability": availability
    }
    return JsonResponse(result)


class SuccessView(ListView):
    template_name = "homefood/success.html"
    #context_object_name = "all_products"

    def get_queryset(self):
        return ""

class ErrorView(ListView):
    template_name = "homefood/error.html"
    #context_object_name = "all_products"

    def get_queryset(self):
        return ""

class AppointmentView(View):
    success_template_name = "homefood/success.html"
    error_template_name = "homefood/error.html"

    def post(self, request):
        try:
            schedule_form = SchedulerForm(request.POST)
            tm = TaskManager()
            # HACK - Starting our task manager on the first request for scheduling
            # Use celery + Rabbitmq instead.
            if not tm.is_running():
                tm.run()

            if schedule_form.is_valid():
                print "here"
                schedule = schedule_form.cleaned_data
                date = schedule.get("scheduleDate")
                time = schedule.get("scheduleTime")
                topic = schedule.get("scheduleTopic")
                interviewee_email = request.user.email
                print "date=" + date + " time=" + time + " topic=" + topic
                msg = ScheduleMessage(schedule_date=date, schedule_time=time, schedule_topic=topic, interviewee_email=interviewee_email)
                tm.schedule(msg)
            else:
                print "Schedule form not valid"
            return render(request, self.success_template_name)
        except Exception:
            return render(request, self.success_template_name)

    def get(self, request):
        upcoming_interviews = {"interviews": []}
        try:
            if request.user.is_active:
                user = request.user
                filter = request.GET.get('filter', None)
                if not filter:
                    # get all interviews
                    upcoming_interviews["interviews"] = ["all_interviews"]
                elif filter == InterviewConstants.INTERVIEW_STATUS_SCHEDULED:
                    upcoming_interviews["interviews"] = AppointmentsDao.get_scheduled_interviews(user)
            print upcoming_interviews
            return JsonResponse(upcoming_interviews)
        except Exception:
            LOG.exception("Error occurred duing GET /appointments for user=%s" % request.user)

# def handler404(request):
#     return render(request, '404.html', status=404)


# def handler500(request):
#     return render(request, '500.html', status=500)

############## User ##############

# class AddUser(CreateView):
#     model = User
#     form_class = AddUserForm
#     success_url = reverse_lazy(INDEX_URL)

project/users/views.py
from django.views.generic import View, ListView
from django.shortcuts import render, reverse, redirect
from django.template import RequestContext
from forms import CustomUserCreationForm, AuthForm
from models import CustomUserManager, CustomUser
from user_backend import CustomUserAuth
from django.contrib.auth import login

from common.util.log.Logger import Logger


class RegisterView(View):
    LOGGER = Logger().get_logger()
    signup_template = "users/register.html"

    def post(self, request):
        try:
            create_user_form = CustomUserCreationForm(request.POST)
            if create_user_form.is_valid():
                user = create_user_form.cleaned_data
                self.LOGGER.info("Registered user email=%s name=%s" %(user.get("email"), user.get("name")))
                user_email = user.get("email")
                user_password = user.get("password1")
                user_name = user.get("name")
                # TODO: Validate password using auth
                # Create user
                CustomUser.objects.create_user(user_email, user_name, user_password)
                self.LOGGER.info("Successful sign up for user email=%s name=%s" % (user_email, user_name))
            else:
                user = create_user_form.cleaned_data
                self.LOGGER.error("Create user form is invalid for form=%s" % str(user))
            return redirect(reverse("homefood:schedule"))
        except Exception as e:
            self.LOGGER.exception("Error during sign up for user name=%s" % str(e))
            return render(request, self.signup_template)


class AuthView(View):
    LOGGER = Logger().get_logger()
    signup_template = "users/register.html"

    def post(self, request):
        try:
            auth_form = AuthForm(request.POST)
            if auth_form.is_valid():
                user_data = auth_form.cleaned_data
                self.LOGGER.info("Authenticating user details=%s" % (str(user_data)))
                user_email = user_data.get("email")
                user_password = user_data.get("password")
                auth = CustomUserAuth()
                user = auth.authenticate(user_email, user_password)
                self.LOGGER.info("Is Authenticated=%s user details=%s" % (str(user.is_authenticated()), str(user_data)))
                # TODO: Login with user name and details
                if not user:
                    self.LOGGER.error("User doesn't exist for user details=%s" % (str(user_data)))
                    return render(request, self.signup_template, RequestContext(request))
                if user.is_active:
                    request.session.set_expiry(2592000)
                    login(request, user)
                self.LOGGER.info("Successfully authenticated user=%s" % (str(user_email)))
            else:
                self.LOGGER.error("AuthForm is not valid for details=%s" % (auth_form.cleaned_data))
            return redirect(reverse("homefood:schedule"))
        except Exception as e:
            self.LOGGER.exception("Error during authentication for user name=%s" % str(e))
            return redirect(reverse("users:signup"))


class SignupView(ListView):
    template_name = "users/register.html"

    def get_queryset(self):
        return ""


class HomeView(ListView):
    template_name = "users/home.html"

    def get_queryset(self):
        return ""

project/homefood/templates/homefood/contact.html
{% extends "homefood/interview_base.html" %}
{% block title %}
    <title>Valley Coaching - Online Coaching for professionals - About</title>
{% endblock %}
{% block navbar %}
              <nav>
                <ul class="nav masthead-nav">
                    <li><a href="{% url 'homefood:index' %}">Home</a></li>
                    <li><a href="{% url 'homefood:syllabus' %}">Syllabus</a></li>
                    <li  class="active"><a href="{% url 'homefood:about' %}">About</a></li>
                </ul>
              </nav>
{% endblock %}

{% block body %}

            <div>
                <p class="lead">
                    You can schedule a mock interview in just three steps.
                </p>
            </div>
            <form id="scheduler" action="{% url 'homefood:schedule' %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-sm-4">
                        <h4 class="cover-heading">1. Select a date</h4>
                        <input id="scheduleDate" name="scheduleDate" type="hidden"/>
                        <div id="calendar">
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <h4 class="cover-heading">2. Choose an available slot</h4>
                        <input id="scheduleTime" name="scheduleTime" type="hidden"/>
                        <div id="availability">
                            <h5 class=\"lead\">Sorry there are no available slots for the date selected :( </h5>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <h4 class="cover-heading">3. Provide an email</h4>
                          <div class="form-group">
                            <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" placeholder="Enter email"/>
                          </div>
                    </div>
                </div>
                <div>
                    <p class="lead">
                        <a class="btn btn-lg btn-default" type="submit" id="scheduleMockInterview"> Schedule Mock Interview</a>
                    </p>
                </div>
            </form>
			<!--<div class="about-inner-section">-->

				<!--&lt;!&ndash;<div class="col-md-6 about-inner-column">&ndash;&gt;-->
                    <!--&lt;!&ndash;<h3 class="sub-heading">Who?</h3>&ndash;&gt;-->
					<!--&lt;!&ndash;<p class="paragraph-text">&ndash;&gt;-->
                            <!--&lt;!&ndash;We are a small group of people with big idea of taking career coaching online.&ndash;&gt;-->
                    <!--&lt;!&ndash;</p>&ndash;&gt;-->

                    <!--&lt;!&ndash;<h3 class="sub-heading">What?</h3>&ndash;&gt;-->
                    <!--&lt;!&ndash;<p class="paragraph-text">&ndash;&gt;-->
                        <!--&lt;!&ndash;We create virtual classrooms with experienced industry professionals to coach&ndash;&gt;-->
                        <!--&lt;!&ndash;everyone aspiring to move to the next level in their career.&ndash;&gt;-->
                    <!--&lt;!&ndash;</p>&ndash;&gt;-->

                    <!--&lt;!&ndash;<h3 class="sub-heading">How?</h3>&ndash;&gt;-->
                    <!--&lt;!&ndash;<p class="paragraph-text">&ndash;&gt;-->
                        <!--&lt;!&ndash;Depending on the class, it would be Google Hangouts, Skype or WebEx.&ndash;&gt;-->
                    <!--&lt;!&ndash;</p>&ndash;&gt;-->

                    <!--&lt;!&ndash;<h3 class="sub-heading">Where?</h3>&ndash;&gt;-->
                    <!--&lt;!&ndash;<p class="paragraph-text">&ndash;&gt;-->
                        <!--&lt;!&ndash;It's all online. So, half-full-half-empty way of saying it would be anywhere in general but nowhere in particular.&ndash;&gt;-->
                    <!--&lt;!&ndash;</p>&ndash;&gt;-->

				<!--&lt;!&ndash;</div>&ndash;&gt;-->

				<!--&lt;!&ndash;<div class="clearfix"> </div>&ndash;&gt;-->
			<!--</div>-->
		<!--</div>-->
	<!--</div>-->
          <!--</div>-->
{% endblock %}

project/homefood/templates/homefood/courses.html
{% extends "homefood/interview_base.html" %}
{% block title %}
    <title>Valley Coaching - Online Coaching for professionals - Courses </title>
{% endblock %}
{% block navbar %}
              <nav>
                <ul class="nav masthead-nav">
                    <li><a href="{% url 'homefood:index' %}">Home</a></li>
                    <li><a href="{% url 'homefood:syllabus' %}">Syllabus</a></li>
                    <li><a href="{% url 'homefood:about' %}">About</a></li>
                </ul>
              </nav>
{% endblock %}

{% block body %}
          <div class="inner cover">
<div class="container">
	<div class="row">
				<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">

					<!-- PRICE ITEM -->
					<div class="panel price panel-white">
						<div class="panel-heading arrow_box text-center">
						<h3> Java Basics & Advanced </h3>
						</div>
						<div class="panel-body text-center">
							<p class="lead" style="font-size:40px"><strong> &#8377;5000 </strong></p>
						</div>
						<ul class="list-group list-group-flush text-center">
							<li class="list-group-item"><i class="icon-ok text-success"></i> Schedule </li>
							<li class="list-group-item"><i class="icon-ok text-success"></i> Syllabus </li>
							<li class="list-group-item"><i class="icon-ok text-success"></i> Mock Interviews </li>
						</ul>
						<div class="panel-footer">
							<a class="btn btn-lg btn-block btn-default" href="https://imjo.in/DzwaRp">Enroll</a>
						</div>
					</div>
					<!-- /PRICE ITEM -->


				</div>

				<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 col-md-offset-1">

					<!-- PRICE ITEM -->
					<div class="panel price panel-white">
						<div class="panel-heading arrow_box text-center">
						<h3> Coding Interview Basics </h3>
						</div>
						<div class="panel-body text-center">
							<p class="lead" style="font-size:40px"><strong>&#8377;10000</strong></p>
						</div>
						<ul class="list-group list-group-flush text-center">
							<li class="list-group-item"><i class="icon-ok text-success"></i> Schedule </li>
							<li class="list-group-item"><i class="icon-ok text-success"></i> Syllabus  </li>
							<li class="list-group-item"><i class="icon-ok text-success"></i> Mock Interviews </li>
						</ul>
						<div class="panel-footer">
							<a class="btn btn-lg btn-block btn-default" href="https://imjo.in/bKWMuW">Enroll</a>

						</div>
					</div>
					<!-- /PRICE ITEM -->


				</div>

				<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 col-md-offset-1">

					<!-- PRICE ITEM -->
					<div class="panel price panel-white">
						<div class="panel-heading arrow_box text-center">
						<h3> Coding Interview Advanced </h3>
						</div>
						<div class="panel-body text-center">
							<p class="lead" style="font-size:40px"><strong>&#8377;15000</strong></p>
						</div>
						<ul class="list-group list-group-flush text-center">
							<li class="list-group-item"><i class="icon-ok text-success"></i> Schedule </li>
							<li class="list-group-item"><i class="icon-ok text-success"></i> Syllabus </li>
							<li class="list-group-item"><i class="icon-ok text-success"></i> 27/7 Mock Interviews </li>
						</ul>
						<div class="panel-footer">
							<a class="btn btn-lg btn-block btn-default" href="#">Enroll</a>
						</div>
					</div>
					<!-- /PRICE ITEM -->


				</div>



			</div>

</div>
          </div>

<!--- col-xs-6 col-sm-6 col-md-3 col-lg-3 --->
{% endblock %}

project/homefood/templates/homefood/error.html
{% extends "homefood/interview_base.html" %}
{% block title %}
    <title>Valley Coaching - Online Coaching for professionals - Home</title>
{% endblock %}
{% block navbar %}
              <nav>
                <ul class="nav masthead-nav">
                    <li><a href="{% url 'homefood:index' %}">Home</a></li>
                    <li><a href="{% url 'homefood:syllabus' %}">Syllabus</a></li>
                    <li><a href="{% url 'homefood:about' %}">About</a></li>
                </ul>
              </nav>
{% endblock %}
{% block body %}
          <div class="inner cover">
            <h1 class="cover-heading" style="color:#e50000;">Uh oh! Something went wrong!</h1>
            <p class="lead">Sorry about that! Please try your request again.</p>
            <p class="lead">
                Return to <a href="{% url 'homefood:schedule' %}" style="color:#86c232;">scheduling mocks</a>
            </p>
          </div>
{% endblock %}

project/homefood/templates/homefood/interview.html
{% extends "homefood/interview_base.html" %}
{% block body %}
          <div class="inner cover">
            <h1 class="cover-heading">Interview Coach</h1>
            <p class="lead">At Interview Coach, you can take virtual classes with the professionals of Silicon Valley to ace tech coding interviews.</p>
            <p class="lead">
              <a href="{% url 'homefood:courses' %}" class="btn btn-lg btn-default">Enroll now</a>
            </p>
          </div>
{% endblock %}

project/homefood/templates/homefood/syllabus.html
{% extends "homefood/interview_base.html" %}
{% block title %}
    <title>Valley Coaching - Online Coaching for professionals - Syllabus </title>
{% endblock %}
{% block navbar %}
              <nav>
                <ul class="nav masthead-nav">
                    <li><a href="{% url 'homefood:index' %}">Home</a></li>
                    <li class="active"><a href="{% url 'homefood:syllabus' %}">Syllabus</a></li>
                    <li><a href="{% url 'homefood:about' %}">About</a></li>
                </ul>
              </nav>
{% endblock %}

{% block body %}
          <div class="inner cover1" style="overflow:scroll;">
                  <h1 class="cover-heading">Syllabus</h1>
                  <table class="table table-dark">
                      <thead>
                        <tr>
                            <th scope="col"></th>
                            <th scope="col"></th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr bgcolor="#696969">

                          <th scope="row">Week 1</th>
                            <td scope="row">
                                  <button type="button" class="btn btn-link"  data-toggle="collapse" data-target="#demo1">Introduction to the course [+]</button>
                                  <div id="demo1" class="collapse">
                                      </br>
                                      <p><b>Introduction to Java and Coding</p>
                                      <p>Basics of Algorithms and Data Structures</p>
                                      <p>Order Complexity</b></p>
                                </div>
                            </td>


                        </tr>
                        <tr bgcolor>
                          <th scope="row">Week 2</th>
                            <td scope="row">
                                  <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#demo2">Arrays [+]</button>
                                  <div id="demo2" class="collapse">
                                      </br>
                                      <p><b>Basics of Arrays</b></p>
                                      <p><b>Sorting & Searching</b></p>
                                      <p><b>Array Interview Problems & Test</b></p>
                                  </div>
                          </td>
                        </tr>
                        <tr bgcolor="#696969">
                          <th scope="row">Week 3</th>

                            <td scope="row">
                                  <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#demo3">Linked Lists [+]</button>
                                  <div id="demo3" class="collapse">
                                      </br>
                                      <p><b>Basics of LinkedLists</b></p>
                                      <p><b>LinkedList Interview Problems</b></p>
                                      <p><b>Advanced LinkedList Problems & Test</b></p>

                                  </div>
                          </td>
                        </tr>
                        <tr bgcolor>
                          <th scope="row">Week 4</th>

                            <td scope="row">
                                  <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#demo4">Trees [+]</button>
                                  <div id="demo4" class="collapse">
                                      </br>
                                     <p><b>Introduction to Trees</b> - Traversals, Binary Trees, Binary Search Trees </p>
                                      <p><b>Tree Interview Problems</b></p>
                                     <p> <b>Advanced Tree Problems & Test</b></p>
                                  </div>
                          </td>
                        </tr>
                        <tr bgcolor="#696969">
                          <th scope="row">Week 5</th>

                            <td scope="row">
                                  <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#demo5"> Graphs [+]</button>
                                  <div id="demo5" class="collapse">
                                      </br>
                                      <p><b>Introduction to Graphs</b> - BFS, DFS, Shortest Path </p>
                                      <p><b>Graph Interview Problems</b></p>
                                      <p><b>Avandced Graph Problems & Test</b></p>
                                  </div>
                          </td>
                        </tr>
                      <tr bgcolor>
                          <th scope="row">Week 6</th>
                          <td scope="row">
                                  <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#demo6">Dynamic Programming [+]</button>
                                  <div id="demo6" class="collapse">
                                      </br>
                                      <p><b>Introduction to Dynamic Programming</b></p>
                                      <p><b>Identifiction of Dynamic Programming Problems</b></p>
                                      <p><b>Dynamic Programming Interview Problems & Test</b></p>

                                  </div>
                          </td>
                        </tr>
                        <tr bgcolor="#696969">
                          <th scope="row">Week 7</th>
                            <td scope="row">
                                  <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#demo7">Mocks & Design [+]</button>
                                  <div id="demo7" class="collapse">
                                      </br>
                                      <p><b>System Design</b></p>
                                      <p><b>Design Interview Questions</b></p>
                                      <p><b>Mock Interviews</b></p>
                                  </div>
                          </td>
                        </tr>
                        <tr bgcolor>
                          <th scope="row">Week 8</th>
                            <td scope="row">
                                  <a class="btn btn-link" data-toggle="collapse" data-target="#demo8" class="btn btn-lg btn-default-blue">Mocks & Design [+]</a>
                                  <div id="demo8" class="collapse">
                                      </br>
                                      <p><b>Mock Interviews</b></p>
                                  </div>

                          </td>
                        </tr>
                      </tbody>
                    </table>
            <p class="lead">
              <a href="{% url 'homefood:enroll' %}" class="btn btn-lg btn-default">Enroll now</a>
            </p>
          </div>
{% endblock %}