project/homefood/urls.py
from django.conf.urls import url, handler404, handler500
from . import views

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "homefood"

urlpatterns = [
    url(r"^$", views.IndexView.as_view(), name="index"),
    url(r'^about/$', views.AboutView.as_view(), name="about"),
    url(r'^syllabus/$', views.SyllabusView.as_view(), name="syllabus"),
    url(r'^courses/$', views.CoursesView.as_view(), name='courses'),
    url(r'^enroll/$', views.EnrollView.as_view(), name='enroll'),
    url(r'^schedule/$', views.ScheduleView.as_view(), name='schedule'),
    url(r'^ajax/availability/$', views.get_availability, name='get_availability'),
    url(r'^appointment/$', views.AppointmentView.as_view(), name="appointment"),
    url(r'^success/$', views.SuccessView.as_view(), name='success'),
    url(r'^error/$', views.ErrorView.as_view(), name='success')
]

urlpatterns += staticfiles_urlpatterns()
#
# handler404 = views.handler404
# handler500 = views.handler500

project/project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^homefood/', include('homefood.urls')),
    url(r'^user/', include('users.urls'))
]

project/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "users"

urlpatterns = [
    url(r'^signup/$', views.SignupView.as_view(), name="signup"),
    url(r'^register/$', views.RegisterView.as_view(), name="register"),
    url(r'^home/$', views.HomeView.as_view(), name="home"),
    url(r'^login/$', views.AuthView.as_view(), name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'users/register.html'}, name='logout'),
]

urlpatterns += staticfiles_urlpatterns()

project/users/models.py
from __future__ import unicode_literals

from django.utils import timezone
import urllib
import uuid

from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.base_user import BaseUserManager
from django.utils.translation import ugettext_lazy as _
# from django.db.models.signals import post_save
# from django.dispatch import receiver


class CustomUserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, name, password, is_staff, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        now = timezone.now()

        if not email:
            raise ValueError('The given email must be set')

        email = self.normalize_email(email)
        print "here"
        user = self.model(email=email,
                          name=name,
                          is_staff=is_staff,
                          is_active=True,
                          last_login=now,
                          date_joined=now,
                          **extra_fields)

        print "here2"
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, name, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, name, password, False, **extra_fields)

    def create_superuser(self, email, name, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_superuser') is not True:
             raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, name, password, True, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    interview_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email =  models.EmailField(unique=True)
    name = models.CharField(max_length=40, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = CustomUserManager()

    def __str__(self):
        return self.name + ", email=" + self.email

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_absolute_url(self):
        return "/user/%s" % urllib.quote(self.email)

    def get_full_name(self):
        '''
        Returns the first_name plus the last_name, with a space in between.
        '''
        full_name = '%s' % self.name
        return full_name.strip()

    def get_short_name(self):
        full_name = '%s' % self.name
        return full_name.strip()

    def email_user(self, subject, message, from_email=None, **kwargs):
        '''
        Sends an email to this User.
        '''
        send_mail(subject, message, from_email, [self.email], **kwargs)

project/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    """
    A form that creates a custom user with privileges, from the given email and
    password
    """
    def __init__(self, *args, **kargs):
        super(CustomUserCreationForm, self).__init__(*args, **kargs)
        # We do this because, by default django requires password1 & password2.
        # But in our case, we only want the user to enter password once.
        self.fields.pop('password2')

    class Meta:
        model = CustomUser
        fields = ("name", "email", "password1")


class AuthForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

project/users/views.py
from django.views.generic import View, ListView
from django.shortcuts import render, reverse, redirect
from django.template import RequestContext
from forms import CustomUserCreationForm, AuthForm
from models import CustomUserManager, CustomUser
from user_backend import CustomUserAuth
from django.contrib.auth import login

from common.util.log.Logger import Logger


class RegisterView(View):
    LOGGER = Logger().get_logger()
    signup_template = "users/register.html"

    def post(self, request):
        try:
            create_user_form = CustomUserCreationForm(request.POST)
            if create_user_form.is_valid():
                user = create_user_form.cleaned_data
                self.LOGGER.info("Registered user email=%s name=%s" %(user.get("email"), user.get("name")))
                user_email = user.get("email")
                user_password = user.get("password1")
                user_name = user.get("name")
                # TODO: Validate password using auth
                # Create user
                CustomUser.objects.create_user(user_email, user_name, user_password)
                self.LOGGER.info("Successful sign up for user email=%s name=%s" % (user_email, user_name))
            else:
                user = create_user_form.cleaned_data
                self.LOGGER.error("Create user form is invalid for form=%s" % str(user))
            return redirect(reverse("homefood:schedule"))
        except Exception as e:
            self.LOGGER.exception("Error during sign up for user name=%s" % str(e))
            return render(request, self.signup_template)


class AuthView(View):
    LOGGER = Logger().get_logger()
    signup_template = "users/register.html"

    def post(self, request):
        try:
            auth_form = AuthForm(request.POST)
            if auth_form.is_valid():
                user_data = auth_form.cleaned_data
                self.LOGGER.info("Authenticating user details=%s" % (str(user_data)))
                user_email = user_data.get("email")
                user_password = user_data.get("password")
                auth = CustomUserAuth()
                user = auth.authenticate(user_email, user_password)
                self.LOGGER.info("Is Authenticated=%s user details=%s" % (str(user.is_authenticated()), str(user_data)))
                # TODO: Login with user name and details
                if not user:
                    self.LOGGER.error("User doesn't exist for user details=%s" % (str(user_data)))
                    return render(request, self.signup_template, RequestContext(request))
                if user.is_active:
                    request.session.set_expiry(2592000)
                    login(request, user)
                self.LOGGER.info("Successfully authenticated user=%s" % (str(user_email)))
            else:
                self.LOGGER.error("AuthForm is not valid for details=%s" % (auth_form.cleaned_data))
            return redirect(reverse("homefood:schedule"))
        except Exception as e:
            self.LOGGER.exception("Error during authentication for user name=%s" % str(e))
            return redirect(reverse("users:signup"))


class SignupView(ListView):
    template_name = "users/register.html"

    def get_queryset(self):
        return ""


class HomeView(ListView):
    template_name = "users/home.html"

    def get_queryset(self):
        return ""

project/users/templates/users/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    {% load staticfiles %}
      {% block title %}
      {% endblock %}
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'interview.css' %}">

    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
  </head>

  <body class="text-center">


    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="container tall-container">

          <div class="masthead clearfix">
            <div class="container inner">
                <a href="{% url 'homefood:index' %}"><h3 class="masthead-brand">Coach</h3></a>
                {% block navbar %}
                {% endblock %}
            </div>
          </div>
            {% block body %}
            {% endblock %}

        </div>

      </div>

    </div>





    <footer id="myFooter">
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <h2 class="logo"><a href="#"> Coach </a></h2>
            </div>
            <div class="col-sm-2">
                <h5>Get started</h5>
                <ul>
                    <li><a href="{% url 'homefood:index' %}">Home</a></li>
                    <li><a href="{% url 'homefood:courses' %}">Courses</a></li>
                </ul>
            </div>
            <div class="col-sm-2">
                <h5>About us</h5>
                <ul>
                    <li><a href="{% url 'homefood:about' %}">About</a></li>
                    <!--<li><a href="#">Contact us</a></li>-->
                    <!--<li><a href="#">Reviews</a></li>-->
                </ul>
            </div>
            <div class="col-sm-2">
                <h5>Contact</h5>
                <ul>
                    <li><a href="#">valleycoachingonline@gmail.com</a></li>
                </ul>
            </div>
               <div class="col-sm-2">
                <h5>Support</h5>
                <ul>
                    <li><a href="#">Feedback</a></li>
                </ul>
            </div>
            <!--<div class="col-sm-2">-->
                <!--<h5>Address</h5>-->
                <!--<ul>-->
                    <!--<li>1855 <br/>Ednamary Way<br/> Mountain View</li>-->
                    <!--<li>California, 94040</li>-->
                <!--</ul>-->
                <!--</ul>-->
            </div>
            <!--<div class="col-sm-3">-->
                <!--<div class="social-networks">-->
                    <!--<a href="#" class="twitter"><i class="fa fa-twitter"></i></a>-->
                    <!--<a href="#" class="facebook"><i class="fa fa-facebook"></i></a>-->
                    <!--<a href="#" class="google"><i class="fa fa-google-plus"></i></a>-->

                <!--</div>-->
                <!--<button type="button" class="btn btn-default">Contact us</button>-->
            <!--</div>-->
        </div>
    </div>
    <div class="footer-copyright">
        <p>© 2018 Valley Coaching All Rights Reserved </p>
    </div>
</footer>




    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="{% static 'popper.min.js' %}"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <script src="{% static 'interview.js' %}"></script>
  </body>
</html>

project/users/templates/users/home.html
{% extends "users/base.html" %}
{% block title %}
    <title>Valley Coaching - Online Coaching for professionals - Home</title>
{% endblock %}
{% block navbar %}
              <nav>
                <ul class="nav masthead-nav">
                    <li class="active"><a href="#">Home</a></li>
                    <li><a href="">About</a></li>
                </ul>
              </nav>
{% endblock %}
{% block body %}
    <div class="row">
        {% if user.is_authenticated %}
            <h3> You're signed in {{user.name}}!</h3>
        {% else %}
            <p>Welcome, new user. Please log in. {{ user.is_authenticated }}</p>
        {% endif %}
    </div>
{% endblock %}

project/users/templates/users/register.html
{% extends "users/base.html" %}
{% block title %}
    <title>Valley Coaching - Online Coaching for professionals - Home</title>
{% endblock %}
{% block navbar %}
            <form class="signinForm" action="{% url 'users:login' %}" method="post">
                {% csrf_token %}
                  <nav>
                      <ul class="nav masthead-nav">
                          <li>
                              <div class="form-group">
                                  <input type="text" class="form-control-custom" name="email" placeholder="username">
                              </div>
                          </li>
                          <li>
                              <div class="form-group">
                                  <input type="password" class="form-control-custom" name="password" placeholder="password">
                              </div>
                          </li>
                          <li>
                            <button type="submit" class="btn btn-default">Log In</button>
                          </li>
                      </ul>
                  </nav>
            </form>
{% endblock %}
{% block body %}
    <div class="row">
        <div class="col-sm-4">
        </div>
            <div class="col-sm-4">
                <div class="card signupFormDiv">
                    <form class="signupForm" action="{% url 'users:register' %}" method="post">
                        {% csrf_token %}
                        <div class="name form-group">
                            <input type="text" class="form-control-custom" id="name" name="name" placeholder="Name"/>
                        </div>
                        <div class="email form-group">
                            <input type="email" class="form-control-custom" id="email" name="email" aria-describedby="emailHelp" placeholder="Email"/>
                        </div>
                        <div class="password form-group">
                            <input type="password" class="form-control-custom" id="password1" name="password1" placeholder="Password"/>
                        </div>
                        <button type="submit" class="btn btn-lg btn-default" id="signupUser">Sign Up</button>
                    </form>
                    <div class="signupFormDivFooter">
                        <p>You can also sign in with </p>
                        <a id="facebook-connect" href="/accounts/facebook/login/" class="fa-stack fa-lg facebook-color social-login-btn"><i class="fa fa-circle fa-stack-2x"></i><i class="fa fa-facebook fa-stack-1x fa-inverse"></i></a>
                        <a id="linkedin-connect" href="/accounts/linkedin/login/" class="fa-stack fa-lg linkedin-color social-login-btn"><i class="fa fa-circle fa-stack-2x"></i><i class="fa fa-linkedin fa-stack-1x fa-inverse"></i></a>
                        <a id="google-connect" href="/accounts/google/login/" class="fa-stack fa-lg google-color social-login-btn"><i class="fa fa-circle fa-stack-2x"></i><i class="fa fa-google fa-stack-1x fa-inverse"></i></a>
                        <a id="github-connect" href="/accounts/github/login/" class="fa-stack fa-lg github-color social-login-btn"><i class="fa fa-circle fa-stack-2x"></i><i class="fa fa-github fa-stack-1x fa-inverse"></i></a>
                    </div>
                </div>
            </div>
        <div class="col-sm-4">
        </div>
    </div>
{% endblock %}